# Generated by Django 3.0.7 on 2021-06-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200912_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(max_length=50)),
                ('reg_email', models.CharField(max_length=70)),
                ('reg_pass', models.CharField(max_length=50)),
                ('reg_address', models.CharField(max_length=100)),
            ],
        ),
    ]
